name: quant_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=2.0.0
  - pandas>=2.2.0
  - matplotlib>=3.9.0
  - scikit-learn>=1.5.0
  - scipy>=1.13.0
  - statsmodels>=0.14.0
  - numba>=0.60.0
  - openpyxl>=3.1.0
  - jupyter
  - notebook
  - pip
  - pip:
    - cython>=0.29.0
    - joblib>=1.3.0
